# Generated by Django 3.2.19 on 2023-05-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
            ],
        ),
    ]
